import discord
import random

INTENTS = discord.Intents.all( )
client = discord.Client( intents = INTENTS )

인격목록 = {
    "LCB 수감자 이상": "img/LCB Yi sang.png",
    "남부 세븐 협회 6과 이상": "img/seven Yi sang.png",
    "어금니 사무소 해결사 이상": "img/Molar Office Yi sang.png",
    "피쿼드호 일등 항해사 이상": "img/The Pequod Yi sang.png",
    "남부 디에치 협회 4과 이상": "img/dieci Yisang.png",
    "LCE E.G.O::초롱 이상": "img/Lantern Yi sang.png",
    "검계 살수 이상": "img/blade Yi sang.png",
    "개화 E.G.O::동백 이상": "img/Spicebush Yi Sang.png",
    "W사 3등급 정리 요원 이상":"img/W corp Yi sang.png",
    "약지 점묘파 스튜던트 이상": "img/The ring Yi Sang.png",
    "로보토미 E.G.O::엄숙한 애도 이상": "img/Solemn Lament Yi Sang.png",
    "남부 리우 협회 3과 이상": "img/Liu Yi sang.png",
    "N사 E.G.O::흉탄 이상": "img/Fell bullet Yi sang.png",
    "흑수 - 오 필두 이상": "img/Heishou_Pack Yi_Sang.png",
    "거미집 검지 아비  이상": "img/The_Index Yi_Sang.png",
    "병아리반 이상" : "img/april fool yisang.png",
    "LCB 수감자 파우스트": "img/LCB Faust.png",
    "W사 2등급 정리 요원 파우스트": "img/W corp faust.png",
    "살아남은 로보토미 직원 파우스트": "img/Lobotomy_Corp Faust.png",
    "남부 츠바이 협회 4과 파우스트": "img/Zwei Faust.png",
    "워더링하이츠 버틀러 파우스트": "img/Wuthering Faust.png",
    "쥐는 자 파우스트": "img/N corp faust.png",
    "남부 세븐 협회 4과 파우스트": "img/Seven Faust.png",
    "로보토미 E.G.O::후회 파우스트": "img/Lobotomy_E.G.O_Regret_Faust.png",
    "검계 살수 파우스트": "img/Blade Faust.png",
    "멀티크랙 사무소 대표 파우스트": "img/MultiCrack_Office_Rep_Faust_Full_Uptied.png",
    "LCE E.G.O::홍염살 파우스트": "img/LCE_E.G.O_Ardor_Blossom_Star_Faust_Full_Uptied.png",
    "흑수 - 묘 필두 파우스트": "img/Heishou_Pack_-_Mao_Branch_Adept_Faust_Full_Uptied.png",
    "동부 시 협회 3과 파우스트": "img/Shi_Assoc._East_Section_3_Faust_Full_Uptied.png",
    "검지 수행자:【쪽지】파우스트": "img/The_Index_Proselyte_Paper_Slip_Faust_Full_Uptied.png",
    "[ 거미집 약지 제자 ] 파우스트": "img/The_House_of_Spiders_The_Ring_Apprentice_Faust_Full_Uptied.png",
    "코끼리반 파우스트" : "img/april fool faust.png",
    "LCB 수감자 돈키호테": "img/LCB_Sinner_Don_Quixote_Full.png",
    "남부 시 협회 5과 부장 돈키호테": "img/Shi_Assoc._South_Section_5_Director_Don_Quixote_Full_Uptied.png",
    "N사 중간 망치 돈키호테": "img/N_Corp._Mittelhammer_Don_Quixote_Full_Uptied.png",
    "로보토미 E.G.O::초롱 돈키호테": "img/Lobotomy_E.G.O_Lantern_Don_Quixote_Full_Uptied.png",
    "검계 살수 돈키호테": "img/Blade_Lineage_Salsu_Don_Quixote_Full_Uptied.png",
    "W사 3등급 정리 요원 돈키호테": "img/W_Corp._L3_Cleanup_Agent_Don_Quixote_Full_Uptied.png",
    "남부 섕크 협회 5과 부장 돈키호테": "img/Cinq_Assoc._South_Section_5_Director_Don_Quixote_Full_Uptied.png",
    "중지 작은 아우 돈키호테": "img/The_Middle_Little_Sister_Don_Quixote_Full_Uptied.png",
    "T사 3등급 징수직 직원 돈키호테": "img/T_Corp._Class_3_Collection_Staff_Don_Quixote_Full_Uptied.png",
    "라만차랜드 실장 돈키호테": "img/The_Manager_of_La_Manchaland_Don_Quixote_Full_Uptied.png",
    "동부 섕크 협회 3과 돈키호테": "img/Cinq_Assoc._East_Section_3_Don_Quixote_Full_Uptied.png",
    "로보토미 E.G.O::사랑과 증오의 이름으로 돈키호테": "img/Lobotomy_E.G.O_In_the_Name_of_Love_and_Hate_Don_Quixote_Full_Uptied.png",
    "흑수 - 미 돈키호테": "img/Heishou_Pack_-_Wei_Branch_Don_Quixote_Full_Uptied.png",
    "검지 대행자 - 개화 E.G.O::대행 돈키호테": "img/The_Index_Proxy_-_Effloresced_E.G.O_Procuration_Don_Quixote_Full_Uptied.png",
    "코끼리반 돈키호테" : "img/april fool donqui.png",
    "LCB 수감자 료슈": "img/LCB_Sinner_Ryōshū_Full.png",
    "남부 세븐 협회 6과 료슈": "img/Seven_Assoc._South_Section_6_Ryōshū_Full_Uptied.png",
    "LCCB 대리 료슈": "img/LCCB_Assistant_Manager_Ryōshū_Full_Uptied.png",
    "남부 리우 협회 4과 료슈": "img/Liu_Assoc._South_Section_4_Ryōshū_Full_Uptied.png",
    "20구 유로지비 료슈": "img/District_20_Yurodivy_Ryōshū_Full_Uptied.png",
    "흑운회 와카슈 료슈": "img/Kurokumo_Clan_Wakashu_Ryōshū_Full_Uptied.png",
    "류.고.파. 주방장 료슈": "img/R.B._Chef_de_Cuisine_Ryōshū_Full_Uptied.png",
    "W사 3등급 정리 요원 료슈": "img/W_Corp._L3_Cleanup_Agent_Ryōshū_Full_Uptied.png",
    "에드가 가문 치프 버틀러 료슈": "img/Edgar_Family_Chief_Butler_Ryōshū_Full_Uptied.png",
    "로보토미 E.G.O::적안 · 참회 료슈": "img/Lobotomy_E.G.O_Red_Eyes_&_Penitence_Ryōshū_Full_Uptied.png",
    "흑수 - 묘 료슈": "img/Heishou_Pack_-_Mao_Branch_Ryōshū_Full_Uptied.png",
    "N사 E.G.O::경멸, 경외 료슈": "img/N_Corp._E.G.O_Contempt,_Awe_Ryōshū_Full_Uptied.png",
    "홍원 방랑무사 료슈": "img/Drifting_Blade_of_Hongyuan_Ryōshū_Full_Uptied.png",
    "로보토미 E.G.O::잔향 · 외로움 료슈": "img/Lobotomy_E.G.O_Faint_Aroma_&_Solitude_Ryōshū_Full_Uptied.png",
    "코끼리반 료슈" : "img/april fool ryoshu.png",
    "LCB 수감자 뫼르소": "img/LCB_Sinner_Meursault_Full.png",
    "남부 리우 협회 6과 뫼르소": "img/Liu_Assoc._South_Section_6_Meursault_Full_Uptied.png",
    "장미스패너 공방 해결사 뫼르소": "img/Rosespanner_Workshop_Fixer_Meursault_Full_Uptied.png",
    "중지 작은 아우 뫼르소": "img/The_Middle_Little_Brother_Meursault_Full_Uptied.png",
    "데드레빗츠 보스 뫼르소": "img/Dead_Rabbits_Boss_Meursault_Full_Uptied.png",
    "W사 2등급 정리 요원 뫼르소": "img/W_Corp._L2_Cleanup_Agent_Meursault_Full_Uptied.png",
    "N사 큰 망치 뫼르소": "img/N_Corp._Großhammer_Meursault_Full_Uptied.png",
    "R사 제 4무리 코뿔소팀 뫼르소": "img/R_Corp._4th_Pack_Rhino_Meursault_Full_Uptied.png",
    "검계 우두머리 뫼르소": "img/Blade_Lineage_Mentor_Meursault_Full_Uptied.png",
    "남부 디에치 협회 4과 부장 뫼르소": "img/Dieci_Assoc._South_Section_4_Director_Meursault_Full_Uptied.png",
    "서부 섕크 협회 3과 뫼르소": "img/Cinq_Assoc._West_Section_3_Meursault_Full_Uptied.png",
    "동부 엄지 카포 IIII 뫼르소": "img/The_Thumb_East_Capo_IIII_Meursault_Full_Uptied.png",
    "라만차랜드 왕자 뫼르소": "img/The_Prince_of_La_Manchaland_Meursault_Full_Uptied.png",
    "로보토미 E.G.O::호넷【변조】뫼르소": "img/Lobotomy_E.G.O_Hornet_Alteration_Meursault_Full_Uptied.png",
    "펭귄반 뫼르소" : "img/april fool mer.png",
    "LCB 수감자 홍루": "img/LCB_Sinner_Hong_Lu_Full.png",
    "흑운회 와카슈 홍루": "img/Kurokumo_Clan_Wakashu_Hong_Lu_Full_Uptied.png",
    "남부 리우 협회 5과 홍루": "img/Liu_Assoc._South_Section_5_Hong_Lu_Full_Uptied.png",
    "W사 2등급 정리 요원 홍루": "img/W_Corp._L2_Cleanup_Agent_Hong_Lu_Full_Uptied.png",
    "갈고리 사무소 해결사 홍루": "img/Hook_Office_Fixer_Hong_Lu_Full_Uptied.png",
    "송곳니 사냥 사무소 해결사 홍루": "img/Fanghunt_Office_Fixer_Hong_Lu_Full_Uptied.png",
    "콩콩이파 두목 홍루": "img/Tingtang_Gang_Gangleader_Hong_Lu_Full_Uptied.png",
    "K사 3등급 적출직 직원 홍루": "img/K_Corp._Class_3_Excision_Staff_Hong_Lu_Full_Uptied.png",
    "남부 디에치 협회 4과 홍루": "img/Dieci_Assoc._South_Section_4_Hong_Lu_Full_Uptied.png",
    "20구 유로지비 홍루": "img/District_20_Yurodivy_Hong_Lu_Full_Uptied.png",
    "마침표 사무소 대표 홍루": "img/Full-Stop_Office_Rep_Hong_Lu_Full_Uptied.png",
    "R사 제 4무리 순록팀 홍루": "img/R_Corp._4th_Pack_Reindeer_Hong_Lu_Full_Uptied.png",
    "홍원 군주 홍루": "img/The_Lord_of_Hongyuan_Hong_Lu_Full_Uptied.png",
    "[ 거미집 약지 아비 ] 홍루": "img/The_House_of_Spiders_The_Ring_Nursefather_Hong_Lu_Full_Uptied.png",
    "코끼리반 홍루" : "img/april fool honglu.png",
    "LCB 수감자 히스클리프": "img/LCB_Sinner_Heathcliff_Full.png",
    "남부 시 협회 5과 히스클리프": "img/Shi_Assoc._South_Section_5_Heathcliff_Full_Uptied.png",
    "N사 작은 망치 히스클리프": "img/N_Corp._Kleinhammer_Heathcliff_Full_Uptied.png",
    "남부 세븐 협회 4과 히스클리프": "img/Seven_Assoc._South_Section_4_Heathcliff_Full_Uptied.png",
    "멀티크랙 사무소 해결사 히스클리프": "img/MultiCrack_Office_Fixer_Heathcliff_Full_Uptied.png",
    "R사 제 4무리 토끼팀 히스클리프": "img/R_Corp._4th_Pack_Rabbit_Heathcliff_Full_Uptied.png",
    "로보토미 E.G.O::여우비 히스클리프": "img/Lobotomy_E.G.O_Sunshower_Heathcliff_Full_Uptied.png",
    "피쿼드호 작살잡이 히스클리프": "img/The_Pequod_Harpooneer_Heathcliff_Full_Uptied.png",
    "남부 외우피 협회 3과 히스클리프": "img/Öufi_Assoc._South_Section_3_Heathcliff_Full_Uptied.png",
    "와일드헌트 히스클리프": "img/Wild_Hunt_Heathcliff_Full_Uptied.png",
    "마침표 사무소 해결사 히스클리프": "img/Full-Stop_Office_Fixer_Heathcliff_Full_Uptied.png",
    "흑운회 와카슈 히스클리프": "img/Kurokumo_Clan_Wakashu_Heathcliff_Full_Uptied.png",
    "W사 4등급 정리 요원 - CCA 히스클리프": "img/W_Corp._L4_Cleanup_Agent_-_CCA_Heathcliff_Full_Uptied.png",
    "흑수 - 유 필두 히스클리프": "img/Heishou_Pack_-_You_Branch_Adept_Heathcliff_Full_Uptied.png",
    "병아리반 히스클리프" : "img/april fool heth.png",
    "LCB 수감자 이스마엘": "img/LCB_Sinner_Ishmael_Full.png",
    "남부 시 협회 5과 이스마엘": "img/Shi_Assoc._South_Section_5_Ishmael_Full_Uptied.png",
    "LCCB 대리 이스마엘": "img/LCCB_Assistant_Manager_Ishmael_Full_Uptied.png",
    "로보토미 E.G.O::출렁임 이스마엘": "img/Lobotomy_E.G.O_Sloshing_Ishmael_Full_Uptied.png",
    "에드가 가문 버틀러 이스마엘": "img/Edgar_Family_Butler_Ishmael_Full_Uptied.png",
    "R사 제 4무리 순록팀 이스마엘": "img/R_Corp._4th_Pack_Reindeer_Ishmael_Full_Uptied.png",
    "남부 리우 협회 4과 이스마엘": "img/Liu_Assoc._South_Section_4_Ishmael_Full_Uptied.png",
    "어금니 보트 센터 해결사 이스마엘": "img/Molar_Boatworks_Fixer_Ishmael_Full_Uptied.png",
    "피쿼드호 선장 이스마엘": "img/The_Pequod_Captain_Ishmael_Full_Uptied.png",
    "서부 츠바이 협회 3과 이스마엘": "img/Zwei_Assoc._West_Section_3_Ishmael_Full_Uptied.png",
    "흑운회 부조장 이스마엘": "img/Kurokumo_Clan_Captain_Ishmael_Full_Uptied.png",
    "가주 후보 이스마엘": "img/Family_Hierarch_Candidate_Ishmael_Full_Uptied.png",
    "정사무소 대표 이스마엘": "img/Jeong's_Office_Rep_Ishmael_Full_Uptied.png",
    "거미집 중지 제자 이스마엘": "img/The_House_of_Spiders_The_Middle_Apprentice_Ishmael_Full_Uptied.png",
    "병아리반 이스마엘" : "img/april fool ish.png",
    "LCB 수감자 로쟈": "img/LCB_Sinner_Rodion_Full.png",
    "LCCB 대리 로쟈": "img/LCCB_Assistant_Manager_Rodion_Full_Uptied.png",
    "N사 중간 망치 로쟈": "img/N_Corp._Mittelhammer_Rodion_Full_Uptied.png",
    "남부 츠바이 협회 5과 로쟈": "img/Zwei_Assoc._South_Section_5_Rodion_Full_Uptied.png",
    "T사 2등급 징수직 직원 로쟈": "img/T_Corp._Class_2_Collection_Staff_Rodion_Full_Uptied.png",
    "흑운회 와카슈 로쟈": "img/Kurokumo_Clan_Wakashu_Rodion_Full_Uptied.png",
    "장미스패너 공방 대표 로쟈": "img/Rosespanner_Workshop_Rep_Rodion_Full_Uptied.png",
    "남부 디에치 협회 4과 로쟈": "img/Dieci_Assoc._South_Section_4_Rodion_Full_Uptied.png",
    "남부 리우 협회 4과 부장 로쟈": "img/Liu_Assoc._South_Section_4_Director_Rodion_Full_Uptied.png",
    "북부 제뱌찌 협회 3과 로쟈": "img/Devyat'_Assoc._North_Section_3_Rodion_Full_Uptied.png",
    "라만차랜드 공주 로쟈": "img/The_Princess_of_La_Manchaland_Rodion_Full_Uptied.png",
    "흑수 - 사 로쟈": "img/Heishou_Pack_-_Si_Branch_Rodion_Full_Uptied.png",
    "로보토미 E.G.O::눈물로 벼려낸 검 로쟈": "img/Lobotomy_E.G.O_The_Sword_Sharpened_with_Tears_Rodion_Full_Uptied.png",
    "R사 제 4무리 순록팀 로쟈": "img/R_Corp._4th_Pack_Reindeer_Rodion_Full_Uptied.png",
    "펭귄반 로쟈" : "img/april fool rodion.png",
    "LCB 수감자 싱클레어": "img/LCB_Sinner_Sinclair_Full.png",
    "남부 츠바이 협회 6과 싱클레어": "img/Zwei_Assoc._South_Section_6_Sinclair_Full_Uptied.png",
    "마리아치 보스 싱클레어": "img/Los_Mariachis_Jefe_Sinclair_Full_Uptied.png",
    "로보토미 E.G.O::홍적 싱클레어": "img/Lobotomy_E.G.O_Red_Sheet_Sinclair_Full_Uptied.png",
    "어금니 보트 센터 해결사 싱클레어": "img/Molar_Boatworks_Fixer_Sinclair_Full_Uptied.png",
    "서부 츠바이 협회 3과 싱클레어": "img/Zwei_Assoc._West_Section_3_Sinclair_Full_Uptied.png",
    "검계 살수 싱클레어": "img/Blade_Lineage_Salsu_Sinclair_Full_Uptied.png",
    "쥐어들 자 싱클레어": "img/The_One_Who_Shall_Grip_Sinclair_Full_Uptied.png",
    "남부 섕크 협회 4과 부장 싱클레어": "img/Cinq_Assoc._South_Section_4_Director_Sinclair_Full_Uptied.png",
    "새벽 사무소 해결사 싱클레어": "img/Dawn_Office_Fixer_Sinclair_Full_Uptied.png",
    "북부 제뱌찌 협회 3과": "img/Devyat'_Assoc._North_Section_3_Sinclair_Full_Uptied.png",
    "중지 작은 아우 싱클레어": "img/The_Middle_Little_Brother_Sinclair_Full_Uptied.png",
    "동부 엄지 솔다토 II 싱클레어": "img/The_Thumb_East_Soldato_II_Sinclair_Full_Uptied.png",
    "흑수 - 유 싱클레어": "img/Heishou_Pack_-_You_Branch_Sinclair_Full_Uptied.png",
    "거미집 소지 제자 싱클레어": "img/The_House_of_Spiders_The_Pinky_Apprentice_Sinclair_Full_Uptied.png",
    "병아리반 싱클레어" : "img/april fool sincl.png",
    "LCB 수감자 오티스": "img/LCB_Sinner_Outis_Full.png",
    "검계 살수 오티스": "img/Blade_Lineage_Salsu_Outis_Full_Uptied.png",
    "G사 부장 오티스": "img/G_Corp._Head_Manager_Outis_Full_Uptied.png",
    "남부 섕크 협회 4과 오티스": "img/Cinq_Assoc._South_Section_4_Outis_Full_Uptied.png",
    "약지 점묘파 스튜던트 오티스": "img/The_Ring_Pointillist_Student_Outis_Full_Uptied.png",
    "남부 세븐 협회 6과 부장 오티스": "img/Seven_Assoc._South_Section_6_Director_Outis_Full_Uptied.png",
    "어금니 사무소 해결사 오티스": "img/Molar_Office_Fixer_Outis_Full_Uptied.png",
    "로보토미 E.G.O::마탄 오티스": "img/Lobotomy_E.G.O_Magic_Bullet_Outis_Full_Uptied.png",
    "워더링하이츠 치프 버틀러 오티스": "img/Wuthering_Heights_Chief_Butler_Outis_Full_Uptied.png",
    "W사 3등급 정리 요원 팀장 오티스": "img/W_Corp._L3_Cleanup_Captain_Outis_Full_Uptied.png",
    "라만차랜드 이발사 오티스": "img/The_Barber_of_La_Manchaland_Outis_Full_Uptied.png",
    "흑수 - 묘 오티스": "img/Heishou_Pack_-_Mao_Branch_Outis_Full_Uptied.png",
    "T사 3등급 강력징수직 직원 오티스": "img/T_Corp._Class_3_VDCU_Staff_Outis_Full_Uptied.png",
    "LCA 우제트 선봉 3팀 팀장 오티스": "img/LCA_Udjat_Vanguard_Team_3_Leader_Outis_Full_Uptied.png",
    "펭귄반 오티스" : "img/april fool outis.png",
    "LCB 수감자 그레고르": "img/LCB_Sinner_Gregor_Full.png",
    "남부 리우 협회 6과 그레고르": "img/Liu_Assoc._South_Section_6_Gregor_Full_Uptied.png",
    "료.고.파. 조수 그레고르": "img/R.B._Sous-chef_Gregor_Full_Uptied.png",
    "장미스패너 공방 해결사 그레고르": "img/Rosespanner_Workshop_Fixer_Gregor_Full_Uptied.png",
    "흑운회 부조장 그레고르": "img/Kurokumo_Clan_Captain_Gregor_Full_Uptied.png",
    "G사 일등대리 그레고르": "img/G_Corp._Manager_Corporal_Gregor_Full_Uptied.png",
    "남부 츠바이 협회 4과 그레고르": "img/Zwei_Assoc._South_Section_4_Gregor_Full_Uptied.png",
    "쌍갈고리 해적단 부선장 그레고르": "img/Twinhook_Pirates_First_Mate_Gregor_Full_Uptied.png",
    "에드가 가문 승계자 그레고르": "img/Edgar_Family_Heir_Gregor_Full_Uptied.png",
    "라만차랜드 신부 그레고르": "img/The_Priest_of_La_Manchaland_Gregor_Full_Uptied.png",
    "불주먹 사무소 생존자 그레고르": "img/Firefist_Office_Survivor_Gregor_Full_Uptied.png",
    "흑수 - 사 그레고르": "img/Heishou_Pack_-_Si_Branch_Gregor_Full_Uptied.png",
    "밤의 송곳 카피타노 그레고르": "img/Night_Awls_Capitano_Gregor_Full_Uptied.png",
    "로보토미 E.G.O::램프 그레고르": "img/Lobotomy_E.G.O_Lamp_Gregor_Full_Uptied.png",
    "LCE E.G.O::AEDD 그레고르": "img/LCE_E.G.O_AEDD_Gregor_Full_Uptied.png",
    "펭귄반 그레고르" : "img/april fool gregor.png",
    "티라노반 베르길리우스" : "img/april fool red eye.png",
}

에고목록 = {
    "오감도 이상" : "img/Crow's_Eye_View_Yi_Sang.png",
    "지난 날 이상" : "img/Bygone_Days_Yi_Sang.png",
    "4번째 성냥불 이상" : "img/4th_Match_Flame_Yi_Sang.png",
    "소망석 이상" : "img/Wishing_Cairn_Yi_Sang.png",
    "차원찢개 이상" : "img/Dimension_Shredder_Yi_Sang.png",
    "흉탄 이상" : "img/Fell_Bullet_Yi_Sang.png",
    "여우비 이상" : "img/Sunshower_Yi_Sang.png",
    "삼천대세계 [三千大世界] 이상" : "img/Great_Trichiliocosm_三千大世界_Yi_Sang.png",
    "표상 방출기 파우스트" : "img/Representation_Emitter_Faust.png",
    "저주못 파우스트" : "img/Hex_Nail_Faust.png",
    "9장 2절 파우스트" : "img/9-2_Faust.png",
    "올가미 파우스트 " : "img/Lasso_Faust.png",
    "물주머니 파우스트" : "img/Fluid_Sac_Faust.png",
    "전봇대 파우스트" : "img/Telepole_Faust.png",
    "흉통 파우스트" : "img/Thoracalgia_Faust.png",
    "명령 : 용해 파우스트" : "img/Command_-_Meltdown_Faust.png",
    "홍염살 파우스트" : "img/Ardor_Blossom_Star_Faust.png",
    "영속 파우스트" : "img/Everlasting_Faust.png",
    "라 샹그레 데 산쵸 돈키호테" : "img/La_Sangre_de_Sancho_Don_Quixote.png",
    "평생 스튜 돈키호테" : "img/Lifetime_Stew_Don_Quixote.png",
    "소망석 돈키호테" : "img/Wishing_Cairn_Don_Quixote.png",
    "전기울음 돈키호테" : "img/Electric_Screaming_Don_Quixote.png",
    "물주머니 돈키호테" : "img/Fluid_Sac_Don_Quixote.png",
    "전봇대 돈키호테" : "img/Telepole_Don_Quixote.png",
    "홍적 돈키호테" : "img/Red_Sheet_Don_Quixote.png",
    "갈망 - 미르칼라 돈키호테" : "img/Yearning-Mircalla_Don_Quixote.png",
    "사랑과 증오의 이름으로 돈키호테" : "img/In_the_Name_of_Love_and_Hate_Don_Quixote.png",
    "삼라염상 료슈" : "img/Forest_for_the_Flames_Ryoshu.png",
    "소다 료슈" : "img/Soda_Ryōshū.png",
    "적안 료슈" : "img/Red_Eyes_Ryōshū.png",
    "맹목 료슈" : "img/Blind_Obsession_Ryōshū.png",
    "4번째 성냥불 료슈" : "img/4th_Match_Flame_Ryōshū.png",
    "적안(開) 료슈" : "img/Red_Eyes_(Open)_Ryōshū.png",
    "흉통 료슈" : "img/Thoracalgia_Ryōshū.png",
    "경멸, 경외 료슈" : "img/Contempt,_Awe_Ryōshū.png",
    "삼천대세계 [三千大世界] 료슈" : "img/Great_Trichiliocosm_三千大世界_Ryōshū.png",
    "타인의 사슬 뫼르소" : "img/Chains_of_Others_Meursault.png",
    "나사빠진 일격 뫼르소" : "img/Screwloose_Wallop_Meursault.png",
    "후회 뫼르소" : "img/Regret_Meursault.png",
    "전기울음 뫼르소" : "img/Electric_Screaming_Meursault.png",
    "집행 뫼르소" : "img/Pursuance_Meursault.png",
    "카포테 뫼르소" : "img/Capote_Meursault.png",
    "갈망 - 미르칼라 뫼르소" : "img/Yearning-Mircalla_Meursault.png",
    "분쇄될 과거 뫼르소" : "img/Crushbound_Past_Meursault.png",
    "허환경 홍루" : "img/Land_of_Illusion_Hong_Lu.png",
    "분홍욕망 홍루" : "img/Roseate_Desire_Hong_Lu.png",
    "소다 홍루" : "img/Soda_Hong_Lu.png",
    "낮은울음 홍루" : "img/Cavernous_Wailing_Hong_Lu.png",
    "올가미 홍루" : "img/Lasso_Hong_Lu.png",
    "차원찢개 홍루" : "img/Dimension_Shredder_Hong_Lu.png",
    "들끓는 부식 홍루" : "img/Effervescent_Corrosion_Hong_Lu.png",
    "영작오 [宁作吾] 홍루" : "img/To_Remain_Oneself_宁作吾_Hong_Lu.png",
    "오혈읍루 [汚血泣淚] 홍루" : "img/Tears_of_the_Tarnished_Blood_汚血泣淚_Hong_Lu.png",
    "시체자루 히스클리프" : "img/Bodysack_Heathcliff.png",
    "홀리데이 히스클리프" : "img/Holiday_Heathcliff.png",
    "AEDD 히스클리프" : "img/AEDD_Heathcliff.png",
    "흉탄 히스클리프" : "img/Fell_Bullet_Heathcliff.png",
    "입주 신고 히스클리프" : "img/Move-in_Reg._Heathcliff.png",
    "전봇대 히스클리프" : "img/Telepole_Heathcliff.png",
    "공즉시색 히스클리프" : "img/Ya_Śūnyatā_Tad_Rūpam_Heathcliff.png",
    "쏠린 관성 히스클리프" : "img/Asymmetrical_Inertia_Heathcliff.png",
    "구속 히스클리프" : "img/Binds_Heathcliff.png",
    "작살박이 이스마엘" : "img/Snagharpoon_Ishmael.png",
    "즉저살 [蝍蛆殺] 이스마엘" : "img/Hundred-Footed_Death_Maggot_蝍蛆殺_Ishmael.png",
    "분홍욕망 이스마엘" : "img/Roseate_Desire_Ishmael.png",
    "카포테 이스마엘" : "img/Capote_Ishmael.png",
    "지난 날 이스마엘" : "img/Bygone_Days_Ishmael.png",
    "홍염살 이스마엘" : "img/Ardor_Blossom_Star_Ishmael.png",
    "날갯짓 이스마엘" : "img/Wingbeat_Ishmael.png",
    "크리스마스 악몽 이스마엘" : "img/Christmas_Nightmare_Ishmael.png",
    "파도의 만가" : "img/Tidal_Elegy_Ishmael.png",
    "맹목 이스마엘" : "img/Blind_Obsession_Ishmael.png",
    "던져지는 것 로쟈" : "img/What_is_Cast_Rodion.png",
    "얼음다리 로쟈" : "img/Rime_Shank_Rodion.png",
    "들끓는 부식 로쟈" : "img/Effervescent_Corrosion_Rodion.png",
    "4번째 성냥불 로쟈" : "img/4th_Match_Flame_Rodion.png",
    "집행 로쟈" : "img/Pursuance_Rodion.png",
    "저주못 로쟈" : "img/Hex_Nail_Rodion.png",
    "핏빛욕망 로쟈" : "img/Sanguine_Desire_Rodion.png",
    "지정 재판 로쟈" : "img/Indicant's_Trial_Rodion.png",
    "지식나무의 가지 싱클레어" : "img/Branch_of_Knowledge_Sinclair.png",
    "낮은울음 싱클레어" : "img/Cavernous_Wailing_Sinclair.png",
    "다가올날 싱클레어" : "img/Impending_Day_Sinclair.png",
    "평생 스튜 싱클레어" : "img/Lifetime_Stew_Sinclair.png",
    "저주못 싱클레어" : "img/Hex_Nail_Sinclair.png",
    "초롱 싱클레어" : "img/Lantern_Sinclair.png",
    "9장 2절 싱클레어" : "img/9-2_Sinclair.png",
    "하모니 싱클레어" : "img/Harmony_Sinclair.png",
    "오혈읍루 [汚血泣淚] 싱클레어" : "img/Tears_of_the_Tarnished_Blood_汚血泣淚_Sinclair.png",
    "토 파토스 마토스 오티스" : "img/To_Páthos_Máthos_Outis.png",
    "난 가위를 낼게, 너는? 오티스" : "img/I'll_Go_fer_Scissors._How_'Bout_You__Outis.png",
    "공즉시색 오티스" : "img/Ya_Śūnyatā_Tad_Rūpam_Outis.png",
    "여우비 오티스" : "img/Sunshower_Outis.png",
    "검은줄기 오티스" : "img/Ebony_Stem_Outis.png",
    "홀리데이 오티스" : "img/Holiday_Outis.png",
    "차원찢개 오티스" : "img/Dimension_Shredder_Outis.png",
    "마탄 오티스" : "img/Magic_Bullet_Outis.png",
    "구속 오티스" : "img/Binds_Outis.png",
    "어느날 갑자기 그레고르" : "img/Suddenly,_One_Day_Gregor.png",
    "눈속임 그레고르" : "img/Legerdemain_Gregor.png",
    "초롱 그레고르" : "img/Lantern_Gregor.png",
    "지난 날 그레고르" : "img/Bygone_Days_Gregor.png",
    "AEDD 그레고르" : "img/AEDD_Gregor.png",
    "엄숙한 애도 그레고르" : "img/Solemn_Lament_Gregor.png",
    "크리스마스 악몽 그레고르" : "img/Christmas_Nightmare_Gregor.png",
    "가시 화원 그레고르" : "img/Garden_of_Thorns_Gregor.png",
    "눈부시지 않은 영광 그레고르" : "img/Unbrilliant_Glory_Gregor.png",
}

test = {
    "티라노반 베르길리우스" : "img/april fool red eye.png",
}

# Discord 클라이언트 객체 생성

# 봇이 준비되었을 때 실행되는 이벤트 핸들러
@client.event
async def on_ready():
    print(f'We have logged in as {client.user}')

@client.event
async def on_message(message):

    if message.author == client.user:
        return

    if message.content.startswith('!인격 룰렛'):

        선택 = random.choice(list(인격목록.keys()))
        이미지 = 인격목록[선택]

        file = discord.File(이미지)

        await message.reply(f"🎲 룰렛 결과!\n👉 **{선택}**", file=file,
        mention_author=False)

    if message.content.startswith('!에고 룰렛'):

        선택 = random.choice(list(에고목록.keys()))
        이미지 = 에고목록[선택]

        file = discord.File(이미지)

        await message.reply(f"🎲 룰렛 결과!\n👉 **{선택}**", file=file,
        mention_author=False)

    if message.content.startswith('!테스트 룰렛'):

        선택 = random.choice(list(test.keys()))
        이미지 = test[선택]

        file = discord.File(이미지)

        await message.reply(f"🎲 룰렛 결과!\n👉 **{선택}**", file=file,
        mention_author=False)

import os
bot.run(os.getenv("TOKEN"))
